[package]
name = "tinyroute"
version = "0.1.0"
edition = "2021"

[features]
default = []
tokio-rt = ["tokio"]
async-std-rt = ["async-std"]
smol-rt = ["smol"]

[dependencies]
bytes = "1.1.0"
flume = "0.10.9"
futures = "0.3.17"
log = "0.4.14"
rand = "0.8.4"
thiserror = "1.0.29"
tokio = { version = "1.11.0", features = ["macros", "net", "rt", "rt-multi-thread", "time", "io-util"], optional = true }
async-std = { version = "1.10.0", optional = true }
smol = { version = "1.2.5", optional = true }

[dev-dependencies]
pretty_env_logger = "0.4.0"
tokio = { version = "1.11.0", features = ["full"] }
